### ISSUE TITLE
Error from markupsafe

### ISSUE THREAD

**Issue by Rob-Fletcher** [grantmcconnaughey/lintly-flake8-github-action#18]
My github action looks like this:
```yaml
  lint:
    needs: check-dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Lint with flake8
        continue-on-error: true
        uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          failIf: new
          args: "--max-line-length=127"
```

When the action runs I am getting a traceback from the markupsafe library:

Traceback (most recent call last):
  File "/usr/local/bin/lintly", line 5, in <module>
    from lintly.cli import main
  File "/usr/local/lib/python3.7/site-packages/lintly/cli.py", line 7, in <module>
    from .builds import LintlyBuild
  File "/usr/local/lib/python3.7/site-packages/lintly/builds.py", line 14, in <module>
    from .backends.github import GitHubBackend
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/__init__.py", line 1, in <module>
    from .github import GitHubBackend  # noqa
  File "/usr/local/lib/python3.7/site-packages/lintly/backends/github.py", line [11](https://github.com/seerai/geodesic-python-api/actions/runs/3449529960/jobs/5757524873#step:3:12), in <module>
    from lintly.formatters import (
  File "/usr/local/lib/python3.7/site-packages/lintly/formatters.py", line 6, in <module>
    from jinja2 import Environment, FileSystemLoader
  File "/usr/local/lib/python3.7/site-packages/jinja2/__init__.py", line [12](https://github.com/seerai/geodesic-python-api/actions/runs/3449529960/jobs/5757524873#step:3:13), in <module>
    from .environment import Environment
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/usr/local/lib/python3.7/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/usr/local/lib/python3.7/site-packages/jinja2/filters.py", line [13](https://github.com/seerai/geodesic-python-api/actions/runs/3449529960/jobs/5757524873#step:3:14), in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/local/lib/python3.7/site-packages/markupsafe/__init__.py)
